# Generated by Django 4.2.1 on 2023-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
                ('phone_number', models.CharField(default=None, max_length=100)),
                ('linkedin', models.CharField(default=None, max_length=400)),
                ('employees', models.CharField(default=None, max_length=100)),
                ('company_website', models.CharField(default=None, max_length=100)),
                ('company_name', models.CharField(default=None, max_length=100)),
                ('location', models.CharField(default=None, max_length=100)),
                ('linkedin_sales_navigator', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
