# Generated by Django 4.2.1 on 2023-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='company_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='company_website',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='employees',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='linkedin',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='linkedin_sales_navigator',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='location',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phone_number',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='title',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
