# Generated by Django 4.2.1 on 2023-05-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_leads_company_name_alter_leads_company_website_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
